name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: | 
        echo "iniciando Login"
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        echo "finaliza Login"

    - name: Build Docker Image
      run: |
        docker container run -p 3000:3000 jesweb/docker-graphql:0.0.2 .

    
    - name: Push Docker Image
      run: |
        docker push jesweb/docker-graphql:0.0.2 .

     
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
